In [1]:
import numpy as np

In [2]:
# efficient memory management hota hai

In [3]:
print("hello World")

hello World


In [4]:
# import sklearn

In [5]:
i=45

In [6]:
print(7)

7


In [7]:
i

45

In [8]:
myarr=np.array([3,6,7,8],np.int32)  #One-D array
myarr
myarr[0]

3

In [9]:
myarr=np.array([[3,6,7,8]])  #two-D array
myarr[0,1]

6

In [10]:
myarr.shape

(1, 4)

In [11]:
myarr.dtype

dtype('int32')

In [12]:
myarr[0,1]=35
myarr

array([[ 3, 35,  7,  8]])

# Arraay creation conversion from other python structure

In [ ]:
listarr=np.array([[1,2,3],[6,5,7],[1,2,1]])
listarr

array([[1, 2, 3],
       [6, 5, 7],
       [1, 2, 1]])

In [14]:
listarr.dtype

dtype('int32')

In [15]:
listarr.shape

(3, 3)

In [16]:
listarr.size

9

In [17]:
np.array({32,35,23}) #no much efficient to create a object

array({32, 35, 23}, dtype=object)

In [18]:
zeroes=np.zeros((2,2))

In [19]:
zeroes

array([[0., 0.],
       [0., 0.]])

In [20]:
zeroes.dtype

dtype('float64')

In [21]:
zeroes.shape
zeroes.size

4

In [22]:
range=np.arange(10)   #give the numpy array not list
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
lspace=np.linspace(1,4,4)   #give the equal linear space dega 1 se 4 mai 4 element 
lspace

array([1., 2., 3., 4.])

In [24]:
lspace=np.linspace(1,5,12)   #give the equal linear space dega 1 se 5 mai 12 element 
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
empty=np.empty((4,6))   # 4,6 ka empty array dega random
empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610994e-306, 1.42413555e-306, 1.78019082e-306],
       [1.37960147e-306, 1.33511562e-306, 2.22518251e-306,
        1.33511969e-306, 1.78022342e-306, 1.05700345e-307],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306, 1.42417222e-306],
       [1.33512648e-306, 7.56596412e-307, 1.42417629e-306,
        8.01108754e-307, 8.34445562e-308, 8.34402698e-308]])

In [26]:
emp_like=np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [27]:
identity=np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
identity.shape

(3, 3)

In [29]:
identity.size

9

In [30]:
arr=np.arange(36)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [31]:
arr=arr.reshape(3,12)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [32]:
arr=arr.ravel()   #sidha ho jayega

In [33]:
arr.shape


(36,)

In [34]:
#Numpy Axis
# 1D --> [1,2,3,4,5]   only 1 axis that is [Axis0] 
# 2D --> [[1,2,3],
#         [4,5,6],
#         [8,2,1]]     only 2 axis that is [Axis0,Axis1] 
#                      Axis0 --> row
#                      Axis1 --> column

In [35]:
x=[[1,2,3],[4,5,6],[8,2,1]]
x

[[1, 2, 3], [4, 5, 6], [8, 2, 1]]

In [36]:
arr=np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 2, 1]])

In [38]:
arr.sum(axis=0)

array([13,  9, 10])

In [39]:
arr.sum(axis=1)


array([ 6, 15, 11])

In [42]:
arr.T  #T-->Transpose

array([[1, 4, 8],
       [2, 5, 2],
       [3, 6, 1]])

In [43]:
arr.flat #give the iterator

In [47]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
8
2
1


In [49]:
arr.ndim   # no of dimension is 2

2

In [51]:
arr.size

9

In [54]:
arr.nbytes  # kitni bytes le rhe hai array 

36

In [59]:
# One-D Array
one=np.array([1,2,10,5,6,7])

In [60]:
one.argmax()  #this is max argumnets and take as function and gave the maxinum agrumnets

2

In [61]:
one.argmin()  #this is max argumnets and take as function and gave the maxinum agrumnets

0

In [64]:
one.argsort()  #array index mil jata hai sort order mai

array([0, 1, 3, 4, 5, 2], dtype=int64)

In [65]:
# 2-D Array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 2, 1]])

In [66]:
arr.argmax()

6

In [67]:
arr.argmin()

0

In [68]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [70]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [71]:
arr.argsort(axis=0)

array([[0, 0, 2],
       [1, 2, 0],
       [2, 1, 1]], dtype=int64)

In [72]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [74]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 8, 2, 1])

In [78]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [8],
       [2],
       [1]])

In [79]:
# Matrix operation
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 2, 1]])

In [80]:
arr2=np.array([[1,2,1],
               [4,5,6],
               [1,2,1]])


In [81]:
arr2

array([[1, 2, 1],
       [4, 5, 6],
       [1, 2, 1]])

In [82]:
arr+arr2

array([[ 2,  4,  4],
       [ 8, 10, 12],
       [ 9,  4,  2]])

In [83]:
# in list 
[34,45]+[23,34]

[34, 45, 23, 34]

In [85]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.82842712, 1.41421356, 1.        ]])

In [86]:
arr.sum()

32

In [87]:
arr.min()

1

In [88]:
arr.max()

8

In [89]:
np.where(arr>5)    #element find

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [90]:
type(np.where(arr>5))    #array ka tuple return

tuple

In [91]:
np.count_nonzero(arr)

9

In [92]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [93]:
arr[1,2]=0

In [94]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [95]:
# How numpy take the less memory 
import sys

In [96]:
py_arr=[0,4,55,4]

In [97]:
np_arr=np.array(py_arr)

In [98]:
sys.getsizeof(1) * len(py_arr)

112

In [99]:
np_arr.itemsize * np_arr.size

16

In [100]:
# Docx scipy.org